[book]
title = "The Linux Luminarium"
description = "The Linux Luminarium: Learning Linux by Leveraging Lightweight Labs and Ludicrous Lessons"
authors = ["benx.guo"]
language = "en"

[preprocessor.gettext]
command = "mdbook-gettext"
optional = true

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/bguo2/the-linux-luminarium-paper"
edit-url-template = "https://github.com/bguo2/the-linux-luminarium-paper/edit/main/{path}"
theme = "theme"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

